<Project Sdk="Microsoft.NET.Sdk">

	<!-- Import tModLoader mod properties -->
	<Import Project="..\tModLoader.targets" />

	<!-- General -->
	<PropertyGroup>
		<GenerateDocumentationFile>true</GenerateDocumentationFile>
		<ResolveAssemblyWarnOrErrorOnTargetArchitectureMismatch>None</ResolveAssemblyWarnOrErrorOnTargetArchitectureMismatch>
	</PropertyGroup>
	<ItemGroup>
	  <PackageReference Include="Krafs.Publicizer" Version="2.3.0">
	    <PrivateAssets>all</PrivateAssets>
	    <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
	  </PackageReference>
	</ItemGroup>
	<ItemGroup>
		<Publicize Include="ReLogic" />
		<Publicize Include="tModLoader" />
		<Publicize Include="FNA" />
		<Publicize Include="Hjson" />
		<DoNotPublicize Include="tModLoader:Terraria.UI.UIElement" />
		<DoNotPublicize Include="tModLoader:Terraria.Main.OnResolutionChanged" />
	</ItemGroup>
	
	<!-- References -->

</Project>